config/routes.rb
Rails.application.routes.draw do

  get 'menu/index'
  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'admin' => 'admin#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'register' => 'users#new'
  get 'cart' => 'sessions#mycart'
  get 'account' => 'users#show'
  get 'logout' => 'sessions#destroy'
  get 'loadMenu' => 'menu#loadMenu'
  get 'menu' => 'menu#index'
  get 'menu/loadMenu' => 'menu#loadMenu'

  post 'menu/addCart' => 'sessions#addToCart'
  post 'menu' => 'sessions#addToCart'
  post 'addCart' => 'sessions#addToCart'
  post 'removeProduct' => 'sessions#removeProductFromCart'
  post 'plusProduct' => 'sessions#plusProduct'
  post 'minusProduct' => 'sessions#minusProduct'
  post 'postOrder' => 'sessions#postOrder'


  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  #get 'admin/index'
  #get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :full_name, presence: true
  validates :full_name, length: { minumum:2, maximum: 30 }

  validates :password, :presence =>true,
            :length => { :minimum => 6, :maximum => 40 },
            :confirmation =>true
  #validates_presence_of :password_confirmation, if: :password_changed?

  validates :telephone, :presence => true
  validates :telephone, length: {minimum: 10, maximum: 20}

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true,
            :format => { :with => email_regex },
            :uniqueness => { :case_sensitive => false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authorize, only: [:new, :create, :index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :email, :password, :telephone, :address1, :address2)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<html>
<head>
  <!-- META DATA -->
  <meta charset="utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="Free Bootstrap Themes by Zerotheme dot com - Free Responsive Html5 Templates">
  <meta name="author" content="https://www.Zerotheme.com">
  <%= javascript_include_tag 'application' %>
  <title>SweetCake</title>

  <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Custom Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Asap:400,700' rel='stylesheet' type='text/css'>

</head>

<body onload="loadMenuIndex();">

<!-- /////////////////////////////////////////Navigation -->
<nav id="page-top" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll">SweetCake</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <%= link_to "Home", root_path, :class => "page-scroll" %>
        </li>
        <li>
          <%= link_to "About", welcome_about_path, :class => "page-scroll" %>
        </li>
        <li>
          <%= link_to "Menu", menu_index_path, :class => "page-scroll" %>
        </li>
        <li>
          <%= link_to "Contact", welcome_contact_path, :class => "page-scroll" %>
        </li>

        <li class="drodown">
          <button id="accountButton" class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">My Account
            <span class="caret"></span></button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
            <%
              if session[:user_id] == nil
            %>
              <li role="presentation">
                <%= link_to register_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-user"></span>
                  Sign Up
                <% end %>
              </li>


              <li role="presentation">
                <%= link_to sessions_create_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-log-in"></span>
                  Log In
                <% end %>
              </li>

            <% else %>
              <li role="presentation">
                <%= link_to cart_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                            <span class="glyphicon glyphicon-shopping-cart"
                                  data-count="
                              <% #Cart cart = (Cart) session.getAttribute("cart")
                                 #if (cart != null)
                                 #	int y = 0
                                 #	int x = cart.getOrder().size()
                                 #	for i in 0..x
                                 #		y += cart.getOrder().get(i).getQuantity()

                                 #	puts (y)
                                  %>"></span>
                  My Cart
                <% end %>
              </li>

              <li role="presentation">
                <%= link_to account_path :id => session[:user_id] do %>
                  <span class="glyphicon glyphicon-home"></span>
                  My Account
                <% end %>
              </li>

              <li role="presentation">
                <%= link_to logout_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-log-out"></span>
                  Log Out
                <% end %>
              </li>
            <%
              end
            %>
          </ul></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<!-- Navigation -->

<%= render 'form', user: @user %>


<!-- FOOTER -->
<footer>
  <div class="wrap-footer">
    <div class="container">
      <div class="row">
        <div class="col-footer col-md-3">
          <h2 class="footer-title">About Us</h2>
          <div class="textwidget">From cupcakes with neighbors in front of the block, we have come to offer sweet delights to all who want to taste our little pieces of happiness.. <br> <br>
            What motivates us is the desire to share the talent of our confectioners with anyone who wants to try out the goodies that come out of their hands.</div>
        </div>
        <div class="col-footer col-md-3">
          <h2 class="footer-title">CONTACT</h2>
          <div class='embed-container maps'>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3164.289259162295!2d-120.7989351!3d37.5246781!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8091042b3386acd7%3A0x3b4a4cedc60363dd!2sMain+St%2C+Denair%2C+CA+95316%2C+Hoa+K%E1%BB%B3!5e0!3m2!1svi!2s!4v1434016649434" width="100%" height="200px" frameborder="0" style="border: 0"></iframe>
          </div>
          <span>JL.Kemacetan timur no.23. block.Q3<br>
							Jakarta-Indonesia</span>
          <span>+6221 888 888 90 <br>
							+6221 888 88891</span>
          <span>info@yourdomain.com</span>
        </div>
      </div>
    </div>
    <div class="bottom-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <p>Copyright 2018 - Designed by Ana-Maria Rusu</p>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li><a href="#"><i class="fa fa-twitter"></i></a>
              </li>
              <li><a href="https://www.facebook.com/Zerotheme"><i class="fa fa-facebook"></i></a>
              </li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a>
              </li>
              <li><a href="#"><i class="fa fa-pinterest"></i></a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li><a href="#">Privacy Policy</a>
              </li>
              <li><a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

<!-- Google Map -->
<script>
    $('.maps').click(function () {
        $('.maps iframe').css("pointer-events", "auto");
    });

    $( ".maps" ).mouseleave(function() {
        $('.maps iframe').css("pointer-events", "none");
    });
</script>
</div>
</body>
</html>

app/views/users/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end  %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Telephone</th>
      <th>Address1</th>
      <th>Address2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.telephone %></td>
        <td><%= user.address1 %></td>
        <td><%= user.address2 %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<html>
<head>
  <!-- META DATA -->
  <meta charset="utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="Free Bootstrap Themes by Zerotheme dot com - Free Responsive Html5 Templates">
  <meta name="author" content="https://www.Zerotheme.com">
  <%= javascript_include_tag 'application' %>
  <title>SweetCake</title>

  <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Custom Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Asap:400,700' rel='stylesheet' type='text/css'>

</head>

<body onload="loadMenuIndex();">

<!-- /////////////////////////////////////////Navigation -->
<nav id="page-top" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll">SweetCake</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <%= link_to "Home", root_path, :class => "page-scroll" %>
        </li>
        <li>
          <%= link_to "About", welcome_about_path, :class => "page-scroll" %>
        </li>
        <li>
          <%= link_to "Menu", menu_index_path, :class => "page-scroll" %>
        </li>
        <li>
          <%= link_to "Contact", welcome_contact_path, :class => "page-scroll" %>
        </li>

        <li class="drodown">
          <button id="accountButton" class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">My Account
            <span class="caret"></span></button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
            <%
              if session[:user_id] == nil
            %>
              <li role="presentation">
                <%= link_to register_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-user"></span>
                  Sign Up
                <% end %>
              </li>


              <li role="presentation">
                <%= link_to sessions_create_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-log-in"></span>
                  Log In
                <% end %>
              </li>

            <% else %>
              <li role="presentation">
                <%= link_to welcome_mycart_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                            <span class="glyphicon glyphicon-shopping-cart">
                            data-count="
                              <% #Cart cart = (Cart) session.getAttribute("cart")
                                 #if (cart != null)
                                 #	int y = 0
                                 #	int x = cart.getOrder().size()
                                 #	for i in 0..x
                                 #		y += cart.getOrder().get(i).getQuantity()

                                 #	puts (y)
                              %>"></span>
                  My Cart
                <% end %>
              </li>

              <li role="presentation">
                <%= link_to welcome_myaccount_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-home"></span>
                  My Account
                <% end %>
              </li>

              <li role="presentation">
                <%= link_to welcome_logout_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-log-out"></span>
                  Log Out
                <% end %>
              </li>
            <%
              end
            %>
          </ul></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<!-- Navigation -->


<%= render 'form', user: @user %>

<%= #link_to 'Back', users_path
%>



<!-- FOOTER -->
<footer>
  <div class="wrap-footer">
    <div class="container">
      <div class="row">
        <div class="col-footer col-md-3">
          <h2 class="footer-title">About Us</h2>
          <div class="textwidget">From cupcakes with neighbors in front of the block, we have come to offer sweet delights to all who want to taste our little pieces of happiness.. <br> <br>
            What motivates us is the desire to share the talent of our confectioners with anyone who wants to try out the goodies that come out of their hands.</div>
        </div>
        <div class="col-footer col-md-3">
          <h2 class="footer-title">CONTACT</h2>
          <div class='embed-container maps'>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3164.289259162295!2d-120.7989351!3d37.5246781!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8091042b3386acd7%3A0x3b4a4cedc60363dd!2sMain+St%2C+Denair%2C+CA+95316%2C+Hoa+K%E1%BB%B3!5e0!3m2!1svi!2s!4v1434016649434" width="100%" height="200px" frameborder="0" style="border: 0"></iframe>
          </div>
          <span>JL.Kemacetan timur no.23. block.Q3<br>
							Jakarta-Indonesia</span>
          <span>+6221 888 888 90 <br>
							+6221 888 88891</span>
          <span>info@yourdomain.com</span>
        </div>
      </div>
    </div>
    <div class="bottom-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <p>Copyright 2018 - Designed by Ana-Maria Rusu</p>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li><a href="#"><i class="fa fa-twitter"></i></a>
              </li>
              <li><a href="https://www.facebook.com/Zerotheme"><i class="fa fa-facebook"></i></a>
              </li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a>
              </li>
              <li><a href="#"><i class="fa fa-pinterest"></i></a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li><a href="#">Privacy Policy</a>
              </li>
              <li><a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

<!-- Google Map -->
<script>
    $('.maps').click(function () {
        $('.maps iframe').css("pointer-events", "auto");
    });

    $( ".maps" ).mouseleave(function() {
        $('.maps iframe').css("pointer-events", "none");
    });
</script>
</div>
</body>
</html>

app/views/users/show.html.erb
<html>
<head>
  <!-- META DATA -->
  <meta charset="utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="Free Bootstrap Themes by Zerotheme dot com - Free Responsive Html5 Templates">
  <meta name="author" content="https://www.Zerotheme.com">
  <%= javascript_include_tag 'application' %>
  <title>SweetCake</title>

  <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Custom Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Asap:400,700' rel='stylesheet' type='text/css'>

</head>

<body onload="loadMenuIndex();">

<!-- /////////////////////////////////////////Navigation -->
<nav id="page-top" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll">SweetCake</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <%= link_to "Home", root_path, :class => "page-scroll" %>
        </li>
        <li>
          <%= link_to "About", welcome_about_path, :class => "page-scroll" %>
        </li>
        <li>
          <%= link_to "Menu", menu_index_path, :class => "page-scroll" %>
        </li>
        <li>
          <%= link_to "Contact", welcome_contact_path, :class => "page-scroll" %>
        </li>

        <li class="drodown">
          <button id="accountButton" class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">My Account
            <span class="caret"></span></button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
            <%
              if session[:user_id] == nil
            %>
              <li role="presentation">
                <%= link_to register_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-user"></span>
                  Sign Up
                <% end %>
              </li>


              <li role="presentation">
                <%= link_to sessions_create_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-log-in"></span>
                  Log In
                <% end %>
              </li>

            <% else %>
              <li role="presentation">
                <%= link_to cart_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                            <span class="glyphicon glyphicon-shopping-cart"
                                  data-count="
                              <% #Cart cart = (Cart) session.getAttribute("cart")
                                 #if (cart != null)
                                 #	int y = 0
                                 #	int x = cart.getOrder().size()
                                 #	for i in 0..x
                                 #		y += cart.getOrder().get(i).getQuantity()

                                 #	puts (y)
                                  %>"></span>
                  My Cart
                <% end %>
              </li>

              <li role="presentation">
                <%= link_to account_path :id => session[:user_id] do %>
                  <span class="glyphicon glyphicon-home"></span>
                  My Account
                <% end %>
              </li>

              <li role="presentation">
                <%= link_to logout_path, :class => "dropdown-item", :role => "menuitem", :tabindex => -1 do %>
                  <span class="glyphicon glyphicon-log-out"></span>
                  Log Out
                <% end %>
              </li>
            <%
              end
            %>
          </ul></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<!-- Navigation -->


	<div class="container text-center">
		<%
			if session[:user_id]
		%>
		<h2>THANK
			YOU FOR BEING OUR CLIENT!</h2>
		<br /> <br />


		<h4>PLEASE
			CHECK YOUR DATA!</h4>
		<hr>

<div id="account">
      <div>
		<div class="align1 alignLeft12">

			<form>
				<fieldset class="accountInfo">

					<label class="align1" for="VEmail">Email</label>
					<div>
            <%= @user.email %>
          </div>

					<br /> <label class="align1" for="VName">Name</label>
					<div>
            <%= @user.full_name %>
          </div>


					<br /> <label class="align1" for="VTelephone">Telephone</label>
					<div>
            <%= @user.telephone %>
          </div>

				</fieldset>
			</form>


		</div>

		<div class="align1 alignRight12">

			<form>
				<fieldset class="accountInfo">

					<label class="align1" for="VAddress">First Address</label>
					<div>
            <%= @user.address1 %>
          </div>

					<br /> <label class="align1" for="VAddress2">Second
						Address</label>
					<div>
            <%= @user.address2 %>
          </div>

				</fieldset>
			</form>


		</div>
		<%
			 else
		%>
		<!-- ERROR MESSAGE -->
		<span id="mesaj"> <% puts ("You are not logged in!") %>
		</span>
		<%
			end
		%>

    </div>

    <div>
      <%= link_to 'Edit', edit_user_path(@user) %> |
      <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
  </div>


<!-- FOOTER -->
<footer>
  <div class="wrap-footer">
    <div class="container">
      <div class="row">
        <div class="col-footer col-md-3">
          <h2 class="footer-title">About Us</h2>
          <div class="textwidget">From cupcakes with neighbors in front of the block, we have come to offer sweet delights to all who want to taste our little pieces of happiness.. <br> <br>
            What motivates us is the desire to share the talent of our confectioners with anyone who wants to try out the goodies that come out of their hands.</div>
        </div>
        <div class="col-footer col-md-3">
          <h2 class="footer-title">CONTACT</h2>
          <div class='embed-container maps'>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3164.289259162295!2d-120.7989351!3d37.5246781!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8091042b3386acd7%3A0x3b4a4cedc60363dd!2sMain+St%2C+Denair%2C+CA+95316%2C+Hoa+K%E1%BB%B3!5e0!3m2!1svi!2s!4v1434016649434" width="100%" height="200px" frameborder="0" style="border: 0"></iframe>
          </div>
          <span>JL.Kemacetan timur no.23. block.Q3<br>
							Jakarta-Indonesia</span>
          <span>+6221 888 888 90 <br>
							+6221 888 88891</span>
          <span>info@yourdomain.com</span>
        </div>
      </div>
    </div>
    <div class="bottom-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <p>Copyright 2018 - Designed by Ana-Maria Rusu</p>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li><a href="#"><i class="fa fa-twitter"></i></a>
              </li>
              <li><a href="https://www.facebook.com/Zerotheme"><i class="fa fa-facebook"></i></a>
              </li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a>
              </li>
              <li><a href="#"><i class="fa fa-pinterest"></i></a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li><a href="#">Privacy Policy</a>
              </li>
              <li><a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

<!-- Google Map -->
<script>
    $('.maps').click(function () {
        $('.maps iframe').css("pointer-events", "auto");
    });

    $( ".maps" ).mouseleave(function() {
        $('.maps iframe').css("pointer-events", "none");
    });
</script>
</div>
</body>
</html>